travis:
  secure:
    BINSTAR_TOKEN: 3UH6njX3yuqy1jUYPYvN5ZoFfmQ62K26Xxl+l9W+arbDRb8qsE5owRGvDYFmmSryVPdCl/ZadsUHfpZDnDqd+0EBnguXw0qZSVYjosmJREFUXVcX2kyJ/kQnlfEJjZJAOo2bMq45PzJRWOUjRg9lr6zZrVVY4/xQ6MWi+Csf2TJIJfQK3sHQNpWhIPD4HwJSoA+IA0TfvQLaXf/t8V9EcjHCkM85gVIVNP5frL/tHLfKvtiDXy7wyfn0D6go9bTuhV77wXUlpSxNQV5R6eLy8pLrmf0BmguCfnixDrehSoVaCvD1jqx2V85PjvN7R8FaQn5Kv2ZkFYK3z8ffnn51L+hVEy1BRrjqli7pLoxo4mlxA3lCO3TM+LJKtla2lMNO+d8i1MOYFPA3fOO30s3usckIPw0Cq42bguhF10ZYvE5awHqlQWk74A6/197BXQKzOSO+d3WjLmxN7h1wpnqL/ayin2tg182S2LxEtqJK0DBJbblCo+gkDcB1X+GdJXf+tcbRYlSdo9+3lGINqgCEmPdiU8cT/4wKYPW6ccZ0npIFu9GEOcqhzPghIXZUX1d1Zmj/B+gH3CBlURDT/8wVWx6jOVCTK++/QpIJtIb4mPIxDHNwy4r4cNh7raDJ4NV6ZC+gNFUVf72IFw6Bi+8mqeXXWLI8jgBbO6xux+iEBoM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
