travis:
  secure:
    BINSTAR_TOKEN: XHt+G5ht59jzwDnGQDeLLl9ukkVTafCNpxvogbidyIkTQ/rgQM0weBrRHaDuX7OH+z8m71bo/rRN9AvNhCSxp4GfvCB8/65D3CuxISWS9xdK/f5I7uqAnEHHpvvf0S/+u2IcwKNLJhqNxF2bbPLuHHCY9OFN4zuFIBM66RYC12mkn5wEgO5uVLt5n2h61I90W+jwCiPRgbv1kv5bmsQSNdQ9Og4WPHAbok+S3F5IKPkHWG4KO6qaWkvOfqeMssCb0mwbatUbQONGAIb3fWkbjX5ThiR9bcnvx7lZAfc5Ly6wgaxzzxq5o0Ge4r0GB/VcsCZV5//0unWNtqhvqka5WxtM+BD/fcG4urJOrfD2sNPtngdco2Dx8K5dae1JN3MRduclb8Nn8RAwHzAZ5rDBCCY064SBdaVQAcbzRcotEWj/tWpz7a3AVaGsoKK172XoiLOLlSuR4p7E5zbjq2rGyvEXpihyS/TaMp7VJYTgWBoFL6gRZBQyY9J88HAgCX5f7fdqO4O71MYE/lcNw+x6r1IlN+rRiCLOOVP3gbSrQba9yXSu9TbaGO9DiN/7uQ4ApWsa3mZwH6yBay5iC9cybsRsj3ftwRNSf0nJMkCzpvg2cQ034Gdr9tIMb2flwb67PdfT3tYv87ngrDvMOYfD1DXcR5QpfvSGqRFUBctLWm8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
